### PYTORCH

Tensor is a multi dimensional array, just like Numpy array.
when  we have numpy arrays what is the need for Tensors.
Tensors are capable of using GPU, due to which tensors get executes much faster and more efficiently compared to Numpy arrays.

In [1]:
import torch
torch.__version__

'1.5.1'

In [2]:
import numpy as np
lst = [3,4,5,6]
arr = np.array(lst)

In [3]:
arr.dtype

dtype('int32')

### Convert Numpy To Pytorch Tensors

In [4]:
tensor = torch.from_numpy(arr)
tensor

tensor([3, 4, 5, 6], dtype=torch.int32)

In [5]:
# Indexing tenosrs similar to Numpy
tensor[:2]

tensor([3, 4], dtype=torch.int32)

In [6]:
tensor[2]

tensor(5, dtype=torch.int32)

In [7]:
tensor[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [8]:
# Disadvantage of from_numpy, both array and tensor uses the same memory location
tensor[3]=100
tensor

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [9]:
arr

array([  3,   4,   5, 100])

In [10]:
# prevent this disadv by using torch.tensor
tensor2 = torch.tensor(arr)
tensor2

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [11]:
tensor2[3]=55
tensor2

tensor([ 3,  4,  5, 55], dtype=torch.int32)

In [12]:
arr

array([  3,   4,   5, 100])

In [13]:
# tensor of zeros and ones
tensor3 = torch.zeros(2,3,dtype=torch.float64)
tensor3

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [14]:
tensor4=torch.ones(3,4)
tensor4.dtype

torch.float32

In [15]:
tensor5=torch.tensor(np.arange(0,15).reshape(5,3))
tensor5

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [16]:
 tensor5[:,1]

tensor([ 1,  4,  7, 10, 13], dtype=torch.int32)

In [17]:
tensor5[:1]

tensor([[0, 1, 2]], dtype=torch.int32)

In [18]:
tensor5[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

# Arthmetic Operation

In [19]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a+b)

tensor([ 7.,  9., 11.])


In [20]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [21]:
c = torch.zeros(3)
c

tensor([0., 0., 0.])

In [22]:
c = torch.add(a,b)
c

tensor([ 7.,  9., 11.])

In [23]:
d = torch.zeros(3)

In [24]:
torch.add(a,b,out=d)

tensor([ 7.,  9., 11.])

In [25]:
### tensor[7,9,11]
torch.add(a,b).sum()

tensor(27.)

In [26]:
### Dot product and Multiplication Operations
x = torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [27]:
x.mul(y)

tensor([12., 20., 30.])

In [28]:
### dot product ---> 3*4 + 4*5 + 5*6 = 12+20+30=62
x.dot(y)

tensor(62.)

In [29]:
### Matrix Multiplication

In [30]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [31]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [32]:
torch.nm(x,y)

AttributeError: module 'torch' has no attribute 'nm'

In [33]:
x@y

tensor([[55., 53.],
        [90., 92.]])

In [35]:
### Back Propagation --> Compute derivative/ slope 

# if y = x**n
#  dy/dx = n*x**n-1
    

In [37]:
x = torch.tensor(4., requires_grad=True)
x

tensor(4., requires_grad=True)

In [39]:
# Backward Propagation
y = x**2
y.backward()
print(x.grad)

tensor(16.)


In [40]:
lst = [[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input = torch.tensor(lst,requires_grad=True)
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [43]:
#y = x**3+x**2
y = torch_input**3 + torch_input**2
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [49]:
z = y.sum()
z

tensor(1040., grad_fn=<SumBackward0>)

In [50]:
z.backward()

In [51]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [52]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])